name: "Deploy"

on:
  push:
    branches: [main]

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest
    outputs:
      cloudflare-tunnel: ${{ steps.filter.outputs.cloudflare-tunnel }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            cloudflare-tunnel:
              - 'cloudflare-tunnel/**'

  deploy:
    name: Deploy
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy cloudflare-tunnel
        if: needs.changes.outputs.cloudflare-tunnel == 'true'
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target cloudflare-tunnel
        env:
          CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
